hard_tabs = false
tab_spaces = 3
max_width=100
# group_imports = "StdExternalCrate"
reorder_imports=true
reorder_modules=true
# trailing_comma = "Vertical"
# imports_granularity = "Preserve"
# struct_field_align_threshold = 20
# indent_style = "Block"
fn_call_width = 60